### ISSUE TITLE
Python Shell log error

### ISSUE THREAD

**Issue by ayoubhamaoui** [aws-samples/amazon-deequ-glue#5]
I'm facing another error with job ```data-quality-controller``` its fail and I can't access to logs ```/aws-glue/python-jobs/output```.
I can only access to Err Logs.
here is the err:
```
Traceback (most recent call last):
  File "/tmp/runscript.py", line 123, in <module>
    runpy.run_path(temp_file_path, run_name='__main__')
  File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/glue-python-scripts-az0bmm4h/deequ-controller.py", line 104, in <module>
ValueError: Error during Controller execution - Check logs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/runscript.py", line 142, in <module>
    raise e_type(e_value).with_traceback(new_stack)
  File "/tmp/glue-python-scripts-az0bmm4h/deequ-controller.py", line 104, in <module>
ValueError: Error during Controller execution - Check logs
```

**Comment by jaidisido** [comment]
That error is thrown when one or more Glue jobs managed by the controller error out [(here)](https://github.com/aws-samples/amazon-deequ-glue/blob/master/src/main/utils/deequ-controller/deequ-controller.py#L108)

So you should look at the ```data-quality-suggestion-analysis-verification-runner``` and ```data-quality-profile-runner``` glue jobs logs as they are the ones that must have failed

**Comment by jaidisido** [comment]
Feel free to reopen if you have more questions
